import handleMovieClick from '../utils/handleMovieClick';

export function useTmdbMovieSelection({
  resetStates,
  setTmdbSeasonsInfo,
  setMovie,
  movie,
  tvSeasons,
  searchGenreInDatabase,
  createGenreInDatabase,
  setSelectedKinds,
  searchStudioInDatabase,
  createStudioInDatabase,
  setSelectedStudios,
  searchCountryInDatabase,
  createCountryInDatabase,
  setSelectedCountries,
  searchLanguageInDatabase,
  createLanguageInDatabase,
  setSelectedLanguages,
  searchDirectorInDatabase,
  createDirectorInDatabase,
  setSelectedDirectors,
  searchScreenwriterInDatabase,
  createScreenwriterInDatabase,
  setSelectedScreenwriters,
  searchCompositorInDatabase,
  createCompositorInDatabase,
  setSelectedMusic,
  searchCastingInDatabase,
  createCastingInDatabase,
  setSelectedCasting,
  searchTagInDatabase,
  createTagInDatabase,
  setSelectedTags,
  setCoverPreview,
}) {
  const handleTmdbMovieClick = async (id, type) => {
    await handleMovieClick(id, type, {
      resetStates,
      setTmdbSeasonsInfo,
      setMovie,
      movie,
      tvSeasons,
      searchGenreInDatabase,
      createGenreInDatabase,
      setSelectedKinds,
      searchStudioInDatabase,
      createStudioInDatabase,
      setSelectedStudios,
      searchCountryInDatabase,
      createCountryInDatabase,
      setSelectedCountries,
      searchLanguageInDatabase,
      createLanguageInDatabase,
      setSelectedLanguages,
      searchDirectorInDatabase,
      createDirectorInDatabase,
      setSelectedDirectors,
      searchScreenwriterInDatabase,
      createScreenwriterInDatabase,
      setSelectedScreenwriters,
      searchCompositorInDatabase,
      createCompositorInDatabase,
      setSelectedMusic,
      searchCastingInDatabase,
      createCastingInDatabase,
      setSelectedCasting,
      searchTagInDatabase,
      createTagInDatabase,
      setSelectedTags,
      setCoverPreview,
    });
  };

  return {
    handleTmdbMovieClick,
  };
}
